### ISSUE TITLE
移植到 Chrome

### ISSUE THREAD

**Issue by Kenqr** [Kenqr/ptt-web-enhanced#2]
有想要移植到 Chrome，但一來考慮到 Chrome 未來可能會支援 Firefox 目前使用的 WebExtensions API，到時候再移植會比較輕鬆，二來是想要先專注在開發新功能上，所以暫時還不會開始進行移植。

**Comment by alan23273850** [comment]
請問現在已經移植到 Chrome Extension 上了嗎 ～

**Comment by Kenqr** [comment]
目前還沒，看起來 Chrome 也沒有要支援 WebExtensions API 的意思，有空會研究看看怎麼移植。

**Comment by danny0838** [comment]
其實移植難度不高，加上一個 polyfill script 即可。很快寫了一個：#6。

**Comment by Kenqr** [comment]
Chrome 版已上架
[PTT Web Enhanced](https://chrome.google.com/webstore/detail/ptt-web-enhanced/afheehakbckodogpkoeakfndigoimokn)

**Comment by alan23273850** [comment]
帥！不過我剛剛試用了一下，會連簽名檔的樓層也算進去，看有沒有辦法排除掉～
而且淺藍色雙箭頭是指本人的意思嗎？

**Comment by Kenqr** [comment]
簽名檔的樓層應該是會分開算的。會有這功能是因為有時候看似簽名檔的部份其實是文章內文的一部份，而且可能會很長。
淺藍色雙箭頭是作者本人沒錯，這個功能可以從選項關掉。
