### ISSUE TITLE
可以寫個 changelog

### ISSUE THREAD

**Issue by danny0838** [Kenqr/ptt-web-enhanced#22]
雖然有版本庫的 commit message，不過還是重點整理一個頁面會比較好查。

格式可以參考我寫的 [WebScrapBook](https://github.com/danny0838/webscrapbook/blob/master/CHANGELOG.md) 和[終結內容農場](https://github.com/danny0838/content-farm-terminator/blob/master/RELEASES.md)。

另外第一個釋出的 Chrome 版是 1.7.3 也可以記錄一下。

**Comment by Kenqr** [comment]
1.7.3 是 ad930d12901ea172a2b2dd31ed6aa050a29ae3dd 這個 commit 嗎？

**Comment by danny0838** [comment]
> 1.7.3 是 [ad930d1](https://github.com/Kenqr/ptt-web-enhanced/commit/ad930d12901ea172a2b2dd31ed6aa050a29ae3dd) 這個 commit 嗎？

是的

**Comment by Kenqr** [comment]
其實一直都有寫 changelog
https://addons.mozilla.org/zh-TW/firefox/addon/ptt-web-enhanced/versions/
前幾個禮拜進英文版頁面看不到，還以為不顯示了，剛剛才發現是因為我只有寫中文版，所以要進中文版網頁才看得到。

**Comment by danny0838** [comment]
原來寫在那裡XD 

Chrome 商店沒有舊版本和改版記錄的功能，我附上 Firefox 版本紀錄的連結好了。
